/*prereq1.0|MIT*/
// prereq.js
// Version - 1.03
//
// by
// Jason Byrne - @jasonbyrne - jbyrne[at]milesplit.com
// Alan Szlosek - aszlosek[a]milesplit.com
//
// http://github.com/milesplit/Prereq
//
var Prereq=(function(s){var c={},n=true,r=false,b,j={},l=function(d){return{}.toString.call(d)=="[object Array]"},x=function(d){return(typeof d=="function")},o=function(d){return d instanceof Object},u=function(d){return(d)?((l(d))?d:[d]):[]},m=function(d){return(x(d))?d:function(){}},e=(function(){var d=s.getElementsByTagName("script");return d[d.length-1]})(),w=(function(){return e?e.getAttribute("data-main")||"":""})(),v=s.head||s.getElementsByTagName("head")[0],h=/\.js$/,q="_",i=function(d){var t=p(d);t.l=n;for(var f=0;f<t.s.length;f++){t.s[f](t.e)}t.s=[]},p=function(d){return j[d]=j[d]||{l:r,e:{},s:[]}},g=function(f,y){if(j[f]){p(f);for(var t=0,d=y.length;t<d;t++){(y[t]!=f)&&c.subscribe(y[t],function(){c.loaded(y)&&i(f)});a(y[t],y[t])}}},a=function(f,t){p(f);var t=h.test(t)?t:t+".js",t=(t.charAt(0)==="/"||t.match(/^\w+:/)?"":w)+t;var d=s.createElement("script");d.src=t;d.async=n;d.id=q+f;d.onload=d.onreadystatechange=function(){var y=d.readyState;if(!y||(/loaded|complete/).test(y)){d.onload=d.onreadystatechange=null;i(f)}};v.appendChild(d)};c.require=function(f,d,C){var t=[],y=[],B=m(C),A=[];(arguments.length==2)&&x(d)?(B=d):(A=l(d)?d:u(d));if(o(f)){for(k in f){t.push(k);l(f[k])?(y=y.concat(f[k])):y.push(f[k])}t=t.join(q)}else{y=u(f);t=y.join(q).replace(h,"")}var z=function(){if(c.loaded(t)){B(_getModule(t).e)}else{c.subscribe(t,B);g(t,y)}};c.loaded(A)?z():c.require(A,z);b=t;return c};c.failover=function(d,f){f=f||5000;if(j[b]){var t=setTimeout(function(){v.removeChild(s.getElementById(q+b));a(b,d)},f);return c.subscribe(b,function(){clearTimeout(t)})}};c.loaded=function(t){t=u(t);for(var f=0,d=t.length;f<d;f++){if(!p(t[f]).l){return r}}return(d==0)?j:n};c.subscribe=function(d,f){p(d).s.push(f);return c};c.define=function(t,d,y){var f={};y?c.require(d,function(){y(f)}):d(f);j[t].e=f;return c};return c})(document);