/*prereq1.0|MIT*/
// prereq.js
// Version - 1.03
//
// by
// Jason Byrne - @jasonbyrne - jbyrne[at]milesplit.com
// Alan Szlosek - aszlosek[a]milesplit.com
//
// http://github.com/milesplit/Prereq
//
var Prereq=(function(s){var c={},n=true,r=false,b,j={},p={},l=function(d){return{}.toString.call(d)=="[object Array]"},x=function(d){return(typeof d=="function")},o=function(d){return d instanceof Object},u=function(d){return(d)?((l(d))?d:[d]):[]},m=function(d){return(x(d))?d:function(){}},e=(function(){var d=s.getElementsByTagName("script");return d[d.length-1]})(),w=(function(){return e?e.getAttribute("data-main")||"":""})(),v=s.head||s.getElementsByTagName("head")[0],i=/\.js$/,q="_",h=function(d){p[d]=p[d]||[];j[d].l=n;for(var f=0;f<p[d].length;f++){p[d][f](j[d].e)}p[d]=[]},g=function(d,t){if(!j[d]){j[d]={n:d,u:t,l:r,e:{}};for(var f=0;f<t.length;f++){(t[f]!=d)&&c.subscribe(t[f],function(){c.loaded(t)&&h(d)});a(t[f],t[f])}}},a=function(f,t){var t=(t||f),t=i.test(t)?t:t+".js",t=(t.charAt(0)==="/"||t.match(/^\w+:/)?"":w)+t;var d=s.createElement("script");d.src=t;d.async=n;d.id=q+f;j[f]={n:f,u:t,l:r,e:{}};d.onload=d.onreadystatechange=function(){var y=d.readyState;if(!y||(/loaded|complete/).test(y)){d.onload=d.onreadystatechange=null;h(f)}};v.appendChild(d)};c.require=function(f,d,C){var t=[],z=[],B=m(C),A=[];(arguments.length==2)&&x(d)?(B=d):(A=l(d)?d:u(d));if(o(f)){for(k in f){t.push(k);l(f[k])?(z=z.concat(f[k])):z.push(f[k])}t=t.join(q)}else{z=u(f);t=z.join(q).replace(i,"")}var y=function(){if(c.loaded(t)){B(j[t].e)}else{c.subscribe(t,B);g(t,z)}};c.loaded(A)?y():c.require(A,y);b=t;return c};c.failover=function(d,t){var f=j[b],t=(t>0)?t:5000;if(f){var y=setTimeout(function(){v.removeChild(s.getElementById(q+b));a(b,d)},t);c.subscribe(b,function(){clearTimeout(y)})}};c.loaded=function(d){d=u(d);for(var f=0;f<d.length;f++){if(!(function(t){if(!j[t]){return r}else{return j[t].l}})(d[f])){return r}}return(d.length==0)?j:n};c.subscribe=function(d,f){p[d]=p[d]||[];p[d].push(f)};c.define=function(t,d,y){var f={};y?c.require(d,function(){y(f)}):d(f);j[t].e=f;return c};return c})(document);